-- INSERT INTO `posts` (`title`, `content`, `img`) VALUES
--   ('1', 'content', 'img'),
--   ('2', 'content', 'img'),
--   ('3', 'content', 'img'),
--   ('4', 'content', 'img'),
--   ('5', 'content', 'img'),
--   ('6', 'content', 'img'),
--   ('7', 'content', 'img'),
--   ('8', 'content', 'img'),
--   ('9', 'content', 'img'),
--   ('10', 'content', 'img'),
--   ('11', 'content', 'img'),
--   ('12', 'content', 'img'),
--   ('13', 'content', 'img'),
--   ('14', 'content', 'img'),
--   ('15', 'content', 'img'),
--   ('16', 'content', 'img'),
--   ('17', 'content', 'img'),
--   ('18', 'content', 'img'),
--   ('19', 'content', 'img'),
--   ('20', 'content', 'img');

INSERT INTO `sections` (`id`, `parent_id`, `name`, `name_rus`) VALUES
  ('1', '0', 'Home', 'Главная'),
  ('2', '0', 'About', 'О нас'),
  ('3', '0', 'Clinics', 'Клиники'),
  ('4', '0', 'Services', 'Услуги и акции'),
  ('5', '0', 'Doctors', 'Врачи'),
  ('6', '0', 'To Patients', 'Пациентам'),
  ('7', '0', 'To Partners', 'Партнерам'),
  ('8', '0', 'Appointment', 'Запись на прием'),
  ('9', '2', 'News', 'Новости'),
  ('10', '2', 'Menegment', 'Менеджмент'),
  ('11', '2', 'License', 'Лицензия'),
  ('12', '2', 'Partners', 'Наши партнеры'),
  ('13', '2', 'Contacts', 'Контакты'),
  ('14', '6', 'Personal Medical Care Programs', 'Персональные программы медобслуживания'),
  ('15', '6', 'Direct Attachment', 'Прямое прикрепление'),
  ('16', '6', 'Payment Methods', 'Способы оплат'),
  ('17', '6', 'Corporate Service', 'Корпоративное обслуживание'),
  ('18', '7', 'Cooperation Programs', 'Программы сотрудничества (CHECK-UP программы, ПМО, ВЛЭК, Мобильный флюромобиль, Оформление медицинских документов)'),
  ('19', '7', 'To Insurance Partners', 'Страховым партнерам');

